//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planifier.DataAccess.Object
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLANIFIEREntities : DbContext
    {
        public PLANIFIEREntities()
            : base("name=PLANIFIEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT_TYPES> ACCOUNT_TYPES { get; set; }
        public virtual DbSet<PROJECT> PROJECTS { get; set; }
        public virtual DbSet<TODO_COMMENTS> TODO_COMMENTS { get; set; }
        public virtual DbSet<TODO_PRIORTIES> TODO_PRIORTIES { get; set; }
        public virtual DbSet<TODO_STATUS> TODO_STATUS { get; set; }
        public virtual DbSet<TODO> TODOS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
