//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planifier.DataAccess.Object
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODO_COMMENTS
    {
        public int CommentId { get; set; }
        public int UserId { get; set; }
        public int ToDoId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreDate { get; set; }
        public Nullable<int> CreUserId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> ModUserId { get; set; }
    
        public virtual TODO TODO { get; set; }
        public virtual USER USER { get; set; }
    }
}
