//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planifier.DataAccess.Object
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TODO()
        {
            this.TODO_COMMENTS = new HashSet<TODO_COMMENTS>();
        }
    
        public int ToDoId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> Estimate { get; set; }
        public string Estimate_Type { get; set; }
        public Nullable<int> PriortyId { get; set; }
        public Nullable<int> Assignee { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreDate { get; set; }
        public Nullable<int> CreUserId { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> ModUserId { get; set; }
    
        public virtual PROJECT PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TODO_COMMENTS> TODO_COMMENTS { get; set; }
        public virtual TODO_PRIORTIES TODO_PRIORTIES { get; set; }
        public virtual TODO_STATUS TODO_STATUS { get; set; }
    }
}
